### ISSUE TITLE
Phishing for surfshark customer login credentials?

### ISSUE THREAD

**Issue by Dynamo1986** [jakeday/SurfShark-VPN-GUI#11]
Not a coder, but no way I would enter anything to this magic box. Why would we trust this? Should just tag into existing set-up. Buyer beware!

**Comment by jakeday** [comment]
@Dynamo1986 If you look at the code, you can see it simply saves what you enter to ~/.surfshark/configs/credentials and does nothing else with it. Also, this is using the ovpn connections which uses different credentials from the other SurfShakr logins.
