### ISSUE TITLE
What if servers change?

### ISSUE THREAD

**Issue by DRCars** [jakeday/SurfShark-VPN-GUI#6]
The server list (servers.json) appears to be static. What will happen if servers come and go or change? I suppose one would have to update the servers.json file. Is that correct? 

It appears the info for the servers.json file may be in the .ovpn files that you already download from "https://my.surfshark.com/vpn/api/v1/server/configurations". Could you update the servers automatically or are you already doing that and I missed it.

**Comment by jakeday** [comment]
@DRCars It would be nice for that file to be dynamic. Unfortunately, it doesn't look like that can be pulled anywhere. I manually parsed it from the list on the SurfShark page. The OVPN files don't contain the friendly name we need for display.

**Comment by DRCars** [comment]
I see why you don't do it now. 

I wrote a Gui frontend for their linux terminal application and it downloads the complete list each time you run it with "friendly" names. It (the terminal application) doesn't use the OVPN files though and the terminal presents problems of its own.

Want more work to do? You could add favorites to the Gui. Just a suggestion, not complaining.

Thanks for the feedback.

**Comment by jakeday** [comment]
@DRCars I'll probably add a startup job that parses the servers list and updates them. I like the idea of favorites, too!

**Comment by DRCars** [comment]
I don't know how you intend to parse the servers list, but if you use the surfshark terminal application, I don't think it will get you the OVPN info for your program. 

It will get a numerical list that includes just a sequential number and the friendly name of server. You then enter a number and it connects to that server. I had to create a method to send keys to the terminal window and pipe the output to a file to load into my Gui frontend. Perhaps, if one is good at BASH scripts or whatever (i'm woefully ignorant) it could be done without sending keystrokes to the terminal. I don't know.

**Comment by DRCars** [comment]
BTW, the OVPN filename  has a unique iudentifier in its name. e.g. "us-stl" would be United States, Saint Louis. Maybe that's how you could do it?

**Comment by editicalu** [comment]
My solution would be to change the structure and put the json file with the serverlist in a package. The program then depends on this package so it is installed when installing. A maintainer of this package can then periodically check for updates and this program shouldn't bother at all. It should only check which openvpn files are present of startup.

**Comment by jakeday** [comment]
The server list is very specific to not only surfshark but also to this app. It's not used for anything else. We need to parse it out and update it on occasion.
