### ISSUE TITLE
IPv6 leak

### ISSUE THREAD

**Issue by editicalu** [jakeday/SurfShark-VPN-GUI#7]
First of all, thanks for this easy-to-use GUI.

When using this application on an IPv6 connection, the IPv6 stack remains active after connecting, leaking data through the non-VPN connection.

## Workaround/Solution

Run the following command before connecting:
```
sysctl -w net.ipv6.conf.all.disable_ipv6=1
```
Run the same after disconnecting, but replace 1 with 0 to restore a connection.

It would be nice if the GUI was able to run these commands on connection and disconnection. :)

**Comment by jakeday** [comment]
@editicalu This has been added in!
