### ISSUE TITLE
How do you uninstall the app? I have tried sudo apt get-remove surfsharkvpngui but it doesn't find the package. 

### ISSUE THREAD

**Issue by nsr01** [jakeday/SurfShark-VPN-GUI#9]

**Comment by QuentiumYT** [comment]
Hello, you can simply run
`bash
sudo rm /usr/bin/surfsharkvpngui
`
which was created by the setup.py file.

Hope it works!

**Comment by nsr01** [comment]
Thanks mate, appreciate it!
